---
title: "Problem2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)
```

Column {data-width=450}
-----------------------------------------------------------------------

```{r}
# First, I remove all the rows contain NA
rest_inspec_clean<- 
  rest_inspec%>%
  drop_na()


```


```{r}
#select out the top 10 popular cuisines in manhattan
Top10<-rest_inspec_clean%>%
  filter(boro == "MANHATTAN")%>%
  group_by(cuisine_description)%>%
  summarize(n = n())%>%
  arrange(desc(n))%>%
  head(10)

Top10_names<-pull(Top10,cuisine_description)

```





### Chart A

```{r}
# Box plots of scores for different cuisines
rest_inspec_clean%>%
  filter(boro == "MANHATTAN")%>%
# only keep top 10 cuisines in the dataset
  filter(cuisine_description %in% Top10_names)%>%
# rename the cuisine
  mutate(cuisine_description = case_when(
    cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" ~ "Latin",
    TRUE ~ cuisine_description
  ))%>%
  mutate(cuisine_description = as.factor(cuisine_description)) %>%
# reorganize the cuisine order
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(
    x = ~cuisine_description, y = ~score, type = "box", 
    color = ~cuisine_description, alpha = 0.5)%>%
  layout(
    title = "Boxplot of scores for Manhattan's 10 most popular cuisines",
    xaxis = list(title = "Cuisine type"),
    yaxis = list(title = "Hygiene score")
  )
  
```

Column {data-width=300}
-----------------------------------------------------------------------

### Chart B

```{r}
#plot Line chart of the proportion of A-level restaurants for each cuisine from 2013 to 2017
rest_inspec_clean%>%
  mutate(time = as.Date(grade_date))%>%
# using string replace to get the year information
  mutate(year = str_replace(time,"\\-[0-9][0-9]\\-[0-9][0-9]$",""))%>%
  filter(cuisine_description %in% Top10_names)%>%
  mutate(cuisine_description = case_when(
    cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" ~ "Latin",
    TRUE ~ cuisine_description
  ))%>%
  group_by(cuisine_description,year)%>%
  summarise(A_percentage = sum(grade == "A") / n())%>%
  plot_ly(
    x = ~year, y = ~A_percentage, color = ~cuisine_description, type = "scatter",mode = "lines", alpha = 0.5)%>%
  layout(
    title = "Line chart of the proportion of A-level restaurants from 2013 to 2017",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Grade A restaurant")
  )

```

### Chart C

```{r}
# Plot Cumulative annual number of Class A restaurants in different zipcodes in Manhattan
rest_inspec_clean%>%
  filter(boro == "MANHATTAN")%>%
  group_by(zipcode)%>%
# calculate how many A level restaurants according to zipcode
  summarise(A_num= sum(grade == "A"))%>%
  mutate(zipcode = as.factor(zipcode))%>%
# reorganize the zipcode order
  mutate(zipcode = fct_reorder(zipcode, A_num)) %>%
  plot_ly(
    x = ~as.factor(zipcode), y = ~A_num, color = ~zipcode,colors = "viridis", type = "bar", alpha = 0.5)%>%
  layout(
    title = "Cumulative annual number of A restaurants cross zipcodes in Manhattan",
    xaxis = list(title = "Zipcode"),
    yaxis = list(title = "Number of A level restaurant")
  )
```




