---
title: "Resume"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: cerulean
  pdf_document:
    toc: yes
---

```{css, echo=FALSE}
.custom-indent {
  margin-left: 30px;
}

.bold-center {
  font-weight: bold;
  font-size: 24px;
  text-align: center;
}
```

<span class="bold-center">Chenshuo Pan</span>


Address: | Tel: 608-628-6056| Email: cp3384@cumc.columbia.edu

## EDUCATION
**Columbia University**     &nbsp;&nbsp; New York, NY


Master of Science in Biostatistics


<p class="custom-indent">• Coursework: Biostatistics, Data Science , Probability , Epidemiology</p>


**University of Wisconsin–Madison Madison**, &nbsp;&nbsp; WI


Bachelor of Science in Statistics


<p class="custom-indent">• Coursework: Data Model, Deep Learning Probability and Math Statistics, Stochastic process, Appl Categorical Data Anal, Data Science with R, Machine Learning</p>


<p class="custom-indent">• Honours: Dean’s List(2021/2022/2023)</p>


## PROFESSIONAL EXPERIENCE
**Baidu Online Network Technology (Beijing) Co., Ltd**  &nbsp;&nbsp; machine learning intern Jun 2023 – Aug 2023

<p class="custom-indent">• Create internal learning materials related to the basics of large models and explain them to sales staff</p>

<p class="custom-indent">• Read literature and assist in the production of internal learning materials including llama, chatglm, falcon and other open source models and multi-modal models</p>

<p class="custom-indent">• Assist in completing llama2 related technical analysis, and test the deployment, fine-tuning and other practices of llama2 based on Baidu's Qianfan platform</p>

<p class="custom-indent">• Participated in the enterprise privatization model deployment project, using Baidu's Wenxin model as a basis to customize large industry models for many enterprises</p>

**CSC Financial Co., Ltd ** &nbsp;&nbsp;Investment Banking Intern Jun 2022 – Aug 2022

<p class="custom-indent">• Participated in the preparation of relevant documents for multiple development bidding of the department, assisted in writing relevant bidding documents, and completed the production of bidding PPT</p>

<p class="custom-indent">• Collected and extracted financial reports and statements of multiple Chinese listed companies in the past three years using Wind Financial Terminal and other data platforms</p>

<p class="custom-indent">• Analyzed the post-listing operations of state-owned and private enterprises and their pattern, and drafted reports</p>

<p class="custom-indent">• Assisted in the completion of the feedback and reply of a project in the group to the questions inquired by the CSRC</p>

**Baidu Online Network Technology (Beijing) Co., Ltd ** &nbsp;&nbsp; Internet Finance Intern Mar 2022 – May 2022

<p class="custom-indent">• Analyzed the current intelligent push, credit evaluation and some other functions and mastered the operation mode and infrastructure logic of Baidu's big data products</p>

<p class="custom-indent">• Analyzed Baidu Cloud and cloud finance, learned the relationship and practical use case of cloud and AI</p>

<p class="custom-indent">• Analyzed the data push algorithm of Little Red Book (a social media and ecommerce platform), and analyzed the big data ecology and components used, and gave industry development prediction</p>


**China Telecom Hongxin Information Technology ** &nbsp;&nbsp; Developer Intern Jun 2020 – Sep 2020

<p class="custom-indent">• Responsible for front-end and back-end interface development, web page and program design</p>

<p class="custom-indent">• Participated in the function development of WeChat public account, and launched a small program smart community beta version</p>

<p class="custom-indent">• Wrote a intelligent community program interface using JavaScript, ran and tested the program afterwards</p>

<p class="custom-indent">• Analyzed project documents and plans, and responsible for the development of back-end functional interfaces based on the spring boot framework</p>

## ACADEMIC PROJECTS AND PUBLICATIONS
**Research on the technical architecture and key technologies of data element value**&nbsp;&nbsp; Jul 2022 – Dec2022

<p class="custom-indent">• Researched on metadata related literature, analyzed the characteristics, and compared the advantages and disadvantages of metadata management systems used by Apache, LinkedIn, and other companies</p>

<p class="custom-indent">• Assisted in building a metadata-based knowledge graph prototype system for team project</p>

<p class="custom-indent">• Compared and adjusted the existing algorithms including linear regression, logistic regression and LGB to obtain higher level of accuracy based on the actual business scenario data, with the goal of detecting outliers/sequences</p>

**Analyzing the Salary of NBA's Player Data Project**&nbsp;&nbsp; Sep 2021 – Dec 2021

<p class="custom-indent">• Collected over 450 pieces of NBA player data for different position, and visualized the data using ggplot2, sunburstR</p>

<p class="custom-indent">• Collected salary data from Kaggle, analyzed and visualized player salary distribution using Python Information Classification: General</p>

<p class="custom-indent">• Analyzed various factors including age, draft order, performance and identified the main influencing factors of salary, and offered suggested salary to both team manager and players accordingly</p>

<p class="custom-indent">• Built a database and trained data for the use of machine learning algorithms including linear regression, classification, and regression tree to predict salary of NBA’s players, using the optimal algorithm to build a well-designed compensation system </p>


**Research on Metadata Management of Data Lake published on SPIE - The International Society for Optical Engineering(Submitted for Index in EI Compendex & Scopus)**

## SKILLS/INTERESTS
Computer Skills: Python, R, Java, C(base), JavaScript, Excel, SQL

Languages: Mandarin (native), English (fluent)

Interests: Basketball, Calligraphy

